name: SharpDevelopMVC Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure environment variables
      run: |
        echo "ftpuser=${{ secrets.SOMEE_USERNAME }}" >> $GITHUB_ENV
        echo "ftppwd=${{ secrets.SOMEE_PASSWORD }}" >> $GITHUB_ENV          
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE      
      
    - name: Restore Packages
      run: nuget restore .\SharpDevelopMVC4\SharpDevelopMVC4.sln

    - name: Build Solution
      run: msbuild.exe .\SharpDevelopMVC4\SharpDevelopMVC4.sln 
                
    - name: Create Build Directory
      run: |
        cd SharpDevelopMVC4
        mkdir _build        
        move /E /Y bin _build\
        move /E /Y App_Data _build\
        move /E /Y Content _build\
        move /E /Y Scripts _build\
        move /E /Y Views _build\
        move /Y Global.asax _build
        move /Y web.config _build
              
    - name: 📂 Publish
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: $ftpuser.somee.com
        username: $ftpuser
        password: $ftppwd
        local-dir: ./SharpDevelopMVC4/_build/" 
        server-dir: www.$ftpuser.somee.com/ 
        
    - name: Check the site
      uses: srt32/uptime@master
      with:
        url-to-hit: "http://$ftpuser.somee.com"     
