# name: .NET

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal

name: SharpDevelopMVC Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the development branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore ./SharpDevelopMVC4/SharpDevelopMVC4.sln

    - name: Build Solution
      run: |     
        msbuild.exe ./SharpDevelopMVC4/SharpDevelopMVC4.sln
        xcopy /bin /_build
        xcopy /App_Data /_build
        xcopy /Content /_build
        xcopy /Scripts /_build
        xcopy ./Views /_build
        xcopy ./Global.asax /_build
        xcopy ./web.config /_build
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SDMVC4Bundle
        path: "./_build"        
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: bernardgabon.somee.com
        username: bernardgabon
        password: ${{ secrets.SOMEE_PASSWORD }}
        local-dir: "./_build/"  
        server-dir: www.bernardgabon.somee.com/ 
        
#   publish:
#       runs-on: windows-latest

#       steps:
#       - uses: actions/checkout@v2        
