name: SharpDevelopMVC Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2    
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE      
      
    - name: Restore Packages
      run: nuget restore .\SharpDevelopMVC4\ASPNETWebApp45.sln

    - name: 🚧 Build Solution
      run: msbuild.exe .\SharpDevelopMVC4\ASPNETWebApp45.sln /t:Rebuild               
              
    - name: 📂 Publish to somee.com
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: "${{ vars.SOMEE_SITENAME }}.somee.com"
        username: "${{ secrets.SOMEE_USERNAME }}"
        password: "${{ secrets.SOMEE_PASSWORD }}"
        local-dir: "./SharpDevelopMVC4/_publish/"
        server-dir: "www.${{ vars.SOMEE_SITENAME }}.somee.com/"
      
    - name: Check the site
      uses: srt32/uptime@master
      with:
        url-to-hit: "${{ vars.SOMEE_SITENAME }}.somee.com"  
        expected-statuses: "200,301"       
